### PR TITLE
Makes JDBC initialization dependent on storage type

### LINKED ISSUE #137: zipkin-java 0.10 /health endpoint shows wrong information?
I am seeing this when I try to hit /health:
```
    "status": "DOWN",
    "error": "org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=localhost)(port=3306)(type=master) : Connection refused"
```

The thing is I am not using mysql backend, I am using cassandra. Also that would never work inside the Docker container since mysql would not be running on "localhost" unless the networking is set to "host" from default (bridge)

### PR DESCRIPTION
**Pull request by adriancole**
Before, auto-configuration would initialize JDBC even when the storage
type was cassandra. This caused the health check to false negative.

One way attempted was to move the yaml config to inside zipkin as
opposed to spring. However, this still ended up being read by auto-
configuration. The end result was making this use the same properties
approach as other storage services, disabling auto-configuration in the
yaml file.

This helps us move towards better modularity #108 

Fixes #137

### CODE REVIEW

**Comment by adriancole** [comment]
tested..

```bash
# when STORAGE_TYPE=cassandra
$ curl -s 'localhost:9411/health'
{"status":"UP","diskSpace":{"status":"UP","total":498920849408,"free":418598928384,"threshold":10485760}}
# when STORAGE_TYPE=mysql
$ curl -s 'localhost:9411/health'
{"status":"UP","diskSpace":{"status":"UP","total":498920849408,"free":418602573824,"threshold":10485760},"db":{"status":"UP","database":"MySQL","hello":1}}
```

File: zipkin-server/src/main/java/zipkin/server/ZipkinMySQLProperties.java [hunk 1]
```diff
@@ -0,0 +1,83 @@
...
+ * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
+ * or implied. See the License for the specific language governing permissions and limitations under
+ * the License.
+ */
+package zipkin.server;
+
+import org.springframework.boot.context.properties.ConfigurationProperties;
+
+@ConfigurationProperties("mysql")
+public class ZipkinMySQLProperties {
```
Comment (adriancole) [inline zipkin-server/src/main/java/zipkin/server/ZipkinMySQLProperties.java]: this class represents the input config from zipkin, which will be mapped directly to non-spring pojo config similar to elasticsearch and cassandra in the future.

File: zipkin-server/src/main/java/zipkin/server/ZipkinServerConfiguration.java [hunk 2]
```diff
@@ -141,19 +143,37 @@ public Object postProcessAfterInitialization(Object bean, String beanName) {
...
+          .driverClassName("org.mariadb.jdbc.Driver")
+          .url(url.toString())
+          .username(mysql.getUsername())
+          .password(mysql.getPassword())
+          .build();
+    }
+
     @Bean JDBCSpanStore jdbcSpanStore() {
-      return new JDBCSpanStore(datasource, new Settings().withRenderSchema(false), listener);
+      return new JDBCSpanStore(dataSource(), new Settings().withRenderSchema(false), listener);
```
Comment (shakuzen) [inline zipkin-server/src/main/java/zipkin/server/ZipkinServerConfiguration.java]: The `ConditionalOnMissingBean` on the `dataSource()` method makes it seem like the user can provide their own `DataSource`, but then this line explicitly uses the `dataSource()` method. You should be able to auto-wire the `DataSource` as this Bean method's parameter, I believe.

```java
@Bean JDBCSpanStore jdbcSpanStore(DataSource dataSource) {
  return new JDBCSpanStore(dataSource, new Settings().withRenderSchema(false), listener);
}
```

Comment (adriancole) [inline zipkin-server/src/main/java/zipkin/server/ZipkinServerConfiguration.java]: great catch!

Comment (adriancole) [inline zipkin-server/src/main/java/zipkin/server/ZipkinServerConfiguration.java]: done
